### ISSUE TITLE
include could not find requested file:wan2respack/config/Type_of_Configure.cmake

### ISSUE THREAD

**Issue by zeen233** [respack-dev/wan2respack#2]
CMake Error at CMakeLists.txt:11 (include):
  include could not find requested file:
  /mnt/md0/DFT/install/wan2respack/config/Type_of_Configure.cmake

**Comment by k-ido** [comment]
$Type_of_Configure is a name of  CMake configure files in the config directory.
For example, if you want to use intel compilers and install wan2respack to build directory, please run the following command in build directory.
`cmake ../ -DCONFIG=intel -DCMAKE_INSTALL_PREFIX=./`

At present, gcc can be also specified instead of intel.

**Comment by zeen233** [comment]
thanks for your helping.. it's work
